version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery_worker
    environment:
      - DJANGO_SETTINGS_MODULE=ecommerce_project.settings

  redis:
    image: redis:latest

  celery_worker:
    build: .
    command: celery -A ecommerce_project worker --pool=solo -l info
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=ecommerce_project.settings
      - CELERY_BROKER_URL=redis://redis:6379/0

networks:
  mynetwork:
    external:
      name: ecommerce_network
